# Generated by Django 3.2.8 on 2021-10-20 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 13, 37, 53, 784897, tzinfo=utc)),
        ),
    ]
