name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/docker-login@v1
        with:
          login-server: ninjagamebackend.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ninjagame-backend/Dockerfile
          push: true
          tags: ninjagame-backend:${{ github.sha }}
          labels: ninjagamebackend.azurecr.io

#       - run: |
#           docker build . -t ninjagamebackend.azurecr.io/ninjagame-backend:${{ github.sha }}
#           docker push ninjagamebackend.azurecr.io/ninjagame-backend:${{ github.sha }}

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
